export type DesignTheme = 'light' | 'dark';

const fontFamily = "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif";
const displayFamily = "'Fraunces', 'Calistoga', Georgia, 'Songti SC', serif";
const monoFamily = "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace";

const light = {
  accent: '#B85B35',
  accentHover: '#A04A27',
  accentActive: '#8A3E1E',
  accentSecondary: '#D98C5A',
  accentText: '#A04A27',
  accentRgb: '184, 91, 53',
  text: '#231F1B',
  textSecondary: '#655E57',
  textTertiary: '#756D63',
  background: '#F7F6F0',
  sunken: '#F1EFE8',
  surface: '#FDFDFB',
  elevated: '#FFFFFF',
  border: '#D8D2C6',
  borderSecondary: '#E8E3D9',
  success: '#4F7A4A',
  successRgb: '79, 122, 74',
  warning: '#9A6818',
  warningRgb: '154, 104, 24',
  error: '#A83A31',
  errorRgb: '168, 58, 49',
  onAccent: '#FFFFFF',
  userMessage: '#EFEAE0',
  fill: 'rgba(35, 31, 27, 0.04)',
  fillSecondary: 'rgba(35, 31, 27, 0.07)',
  fillStrong: 'rgba(35, 31, 27, 0.10)',
} as const;

const dark = {
  accent: '#E27B55',
  accentHover: '#EC8A65',
  accentActive: '#D16C46',
  accentSecondary: '#E5A07C',
  accentText: '#EC8A65',
  accentRgb: '226, 123, 85',
  text: '#ECE6DE',
  textSecondary: '#B5ADA3',
  textTertiary: '#988F84',
  background: '#161513',
  sunken: '#100F0E',
  surface: '#1C1B19',
  elevated: '#252320',
  border: '#756B60',
  borderSecondary: '#6B6259',
  success: '#86B875',
  successRgb: '134, 184, 117',
  warning: '#E0B05C',
  warningRgb: '224, 176, 92',
  error: '#E07B6B',
  errorRgb: '224, 123, 107',
  onAccent: '#16100B',
  userMessage: '#2C2925',
  fill: 'rgba(236, 230, 222, 0.08)',
  fillSecondary: 'rgba(236, 230, 222, 0.12)',
  fillStrong: 'rgba(236, 230, 222, 0.18)',
} as const;

export const designTokens = {
  color: { light, dark },
  typography: {
    body: fontFamily,
    display: displayFamily,
    mono: monoFamily,
    baseSize: 15,
    lineHeight: 1.6,
  },
  spacing: {
    base: 8,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    control: 8,
    surface: 12,
    large: 16,
  },
  width: {
    reading: 760,
    management: 1200,
  },
  motion: {
    duration: { fast: 120, base: 180, slow: 240 },
    easing: 'cubic-bezier(0.2, 0, 0, 1)',
  },
  shadow: {
    xs: '0 1px 2px rgba(35, 31, 27, 0.04)',
    sm: '0 2px 8px rgba(35, 31, 27, 0.05)',
    md: '0 8px 24px rgba(35, 31, 27, 0.07)',
    darkXs: '0 1px 2px rgba(0, 0, 0, 0.28)',
    darkSm: '0 2px 8px rgba(0, 0, 0, 0.34)',
    darkMd: '0 8px 24px rgba(0, 0, 0, 0.42)',
  },
} as const;

export function getCssVariables(theme: DesignTheme): Record<`--${string}`, string> {
  const color = designTokens.color[theme];
  const shadow = theme === 'dark'
    ? { xs: designTokens.shadow.darkXs, sm: designTokens.shadow.darkSm, md: designTokens.shadow.darkMd }
    : designTokens.shadow;

  return {
    '--accent': color.accent,
    '--accent-hover': color.accentHover,
    '--accent-active': color.accentActive,
    '--accent-secondary': color.accentSecondary,
    '--accent-text': color.accentText,
    '--accent-rgb': color.accentRgb,
    '--accent-soft': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.14' : '0.07'})`,
    '--accent-soft-strong': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.22' : '0.12'})`,
    '--accent-bg': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.14' : '0.07'})`,
    '--accent-border': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.22' : '0.12'})`,
    '--color-overlay': theme === 'dark' ? 'rgba(0, 0, 0, 0.60)' : 'rgba(0, 0, 0, 0.45)',
    '--gradient-accent': color.accent,
    '--foreground': color.text,
    '--muted': color.sunken,
    '--muted-foreground': color.textSecondary,
    '--background': color.background,
    '--card': color.surface,
    '--border': color.border,
    '--border-secondary': color.borderSecondary,
    '--color-primary': color.accent,
    '--color-primary-rgb': color.accentRgb,
    '--color-text': color.text,
    '--color-text-secondary': color.textSecondary,
    '--color-text-tertiary': color.textTertiary,
    '--color-text-placeholder': color.textTertiary,
    '--color-bg-body': color.background,
    '--color-bg-sunken': color.sunken,
    '--color-bg-container': color.surface,
    '--color-bg-container-secondary': color.sunken,
    '--color-bg-elevated': color.elevated,
    '--color-bg-elevated-blur': color.elevated,
    '--color-border': color.border,
    '--color-border-secondary': color.borderSecondary,
    '--color-success': color.success,
    '--color-success-rgb': color.successRgb,
    '--color-error': color.error,
    '--color-error-rgb': color.errorRgb,
    '--color-warning': color.warning,
    '--color-warning-rgb': color.warningRgb,
    '--color-fill': color.fill,
    '--color-fill-secondary': color.fillSecondary,
    '--color-fill-strong': color.fillStrong,
    '--color-text-on-accent': color.onAccent,
    '--font-family': designTokens.typography.body,
    '--font-family-display': designTokens.typography.display,
    '--font-family-serif': designTokens.typography.display,
    '--font-family-mono': designTokens.typography.mono,
    '--font-weight-light': '300',
    '--font-weight-regular': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    '--font-weight-bold': '700',
    '--font-size-base': `${designTokens.typography.baseSize}px`,
    '--line-height-base': String(designTokens.typography.lineHeight),
    '--spacing-xs': '4px',
    '--spacing-sm': '8px',
    '--spacing-md': '16px',
    '--spacing-lg': '24px',
    '--spacing-xl': '32px',
    '--spacing-xxl': '48px',
    '--spacing-2xl': '40px',
    '--spacing-3xl': '56px',
    '--spacing-4xl': '72px',
    '--radius-sm': `${designTokens.radius.control}px`,
    '--radius-control': `${designTokens.radius.control}px`,
    '--radius-surface': `${designTokens.radius.surface}px`,
    '--radius-md': `${designTokens.radius.surface}px`,
    '--radius-lg': `${designTokens.radius.large}px`,
    '--radius-xl': `${designTokens.radius.large}px`,
    '--radius-2xl': `${designTokens.radius.large}px`,
    '--radius-3xl': `${designTokens.radius.large}px`,
    '--shadow-xs': shadow.xs,
    '--shadow-sm': shadow.sm,
    '--shadow-md': shadow.md,
    '--shadow-lg': shadow.md,
    '--shadow-xl': shadow.md,
    '--shadow-accent': shadow.sm,
    '--shadow-accent-lg': shadow.md,
    '--shadow-accent-glow': shadow.sm,
    '--shadow-context-menu': shadow.md,
    '--shadow-floating-input': shadow.md,
    '--motion-fast': `${designTokens.motion.duration.fast}ms`,
    '--motion-base': `${designTokens.motion.duration.base}ms`,
    '--motion-slow': `${designTokens.motion.duration.slow}ms`,
    '--motion-ease': designTokens.motion.easing,
    '--ease-out': designTokens.motion.easing,
    '--ease-in-out': designTokens.motion.easing,
    '--ease-spring': designTokens.motion.easing,
    '--ease-soft-spring': designTokens.motion.easing,
    '--ease-smooth': designTokens.motion.easing,
    '--ease-out-expo': designTokens.motion.easing,
    '--dur-instant': 'var(--motion-fast)',
    '--dur-fast': 'var(--motion-fast)',
    '--dur': 'var(--motion-base)',
    '--dur-slow': 'var(--motion-slow)',
    '--dur-page': 'var(--motion-slow)',
    '--transition-page': 'var(--motion-slow) var(--motion-ease)',
    '--user-msg-bg': color.userMessage,
    '--user-msg-accent': color.accent,
    '--msg-bubble-padding': '12px 16px',
    '--content-max': `${designTokens.width.reading}px`,
    '--management-max': `${designTokens.width.management}px`,
    '--page-section-gap': '24px',
    '--card-content-padding': '24px',
    '--color-bg-section': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.10' : '0.025'})`,
    '--sidebar-width-expanded': '272px',
    '--sidebar-width-collapsed': '0px',
    '--header-height': '56px',
    '--header-blur': 'none',
    '--shadow-subtle-glow': 'none',
    '--gemini-gradient': 'none',
    // hljs syntax highlighting token colors (managed centrally for both themes)
    '--hljs-keyword': theme === 'dark' ? '#E0A07C' : '#d73a49',
    '--hljs-string': theme === 'dark' ? '#9ECE8E' : '#032f62',
    '--hljs-comment': theme === 'dark' ? '#847D6E' : '#6a737d',
    '--hljs-number': theme === 'dark' ? '#E5B567' : '#005cc5',
    '--hljs-title': theme === 'dark' ? '#7FB0D8' : '#6f42c1',
    '--hljs-variable': theme === 'dark' ? '#E08B7C' : '#005cc5',
  };
}

export function applyDesignTokens(theme: DesignTheme): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  root.dataset.theme = theme;
  for (const [name, value] of Object.entries(getCssVariables(theme))) {
    root.style.setProperty(name, value);
  }
}
