export type DesignTheme = 'light' | 'dark';

const fontFamily = "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif";
const displayFamily = "'Fraunces', 'Calistoga', Georgia, 'Songti SC', serif";
const monoFamily = "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace";

// Local Graph palette — deep-space blue/violet + neon cyan (tech accent zone,
// intentionally decoupled from the warm Claude palette).
const graphLight = {
  bgStart: '#F5F7FC',
  bgEnd: '#E9EDF7',
  nodeFresh: '#0E7490',
  nodeMid: '#2563EB',
  nodeStale: '#B45309',
  nodeInactive: '#64748B',
  nodeStroke: '#FFFFFF',
  edgeLink: '#0E7490',
  edgeTerm: '#94A3B8',
  edgeSimilar: '#6366F1',
  halo: '#0E7490',
  haloRgb: '14, 116, 144',
  label: '#475569',
} as const;

const graphDark = {
  bgStart: '#0E1220',
  bgEnd: '#161A2E',
  nodeFresh: '#22D3EE',
  nodeMid: '#60A5FA',
  nodeStale: '#F59E0B',
  nodeInactive: '#5B6B84',
  nodeStroke: '#0E1220',
  edgeLink: '#22D3EE',
  edgeTerm: '#3B4863',
  edgeSimilar: '#818CF8',
  halo: '#22D3EE',
  haloRgb: '34, 211, 238',
  label: '#9FB0C9',
} as const;

const light = {
  accent: '#B85B35',
  accentHover: '#A04A27',
  accentActive: '#8A3E1E',
  accentSecondary: '#D98C5A',
  accentText: '#A04A27',
  accentRgb: '184, 91, 53',
  text: '#231F1B',
  textSecondary: '#655E57',
  textTertiary: '#756D63',
  background: '#F7F6F0',
  sunken: '#F1EFE8',
  surface: '#FDFDFB',
  elevated: '#FFFFFF',
  border: '#D8D2C6',
  borderSecondary: '#E8E3D9',
  success: '#4F7A4A',
  successRgb: '79, 122, 74',
  warning: '#9A6818',
  warningRgb: '154, 104, 24',
  error: '#A83A31',
  errorRgb: '168, 58, 49',
  onAccent: '#FFFFFF',
  userMessage: '#EFEAE0',
  fill: 'rgba(35, 31, 27, 0.04)',
  fillSecondary: 'rgba(35, 31, 27, 0.07)',
  fillStrong: 'rgba(35, 31, 27, 0.10)',
} as const;

// Dark palette — Claude warm-paper base, rebuilt for contrast (Dark/i18n/Layout
// spec §A): background steps pulled apart (sunken→background→surface→elevated),
// four text tiers ≥ WCAG AA on their host surfaces, semantic colors tuned for
// dark tint chips. Verified pairs live in the spec's contrast matrix.
const dark = {
  accent: '#E9855F',
  accentHover: '#F0936E',
  accentActive: '#D97450',
  accentSecondary: '#E8A583',
  accentText: '#F09B7A',
  accentRgb: '233, 133, 95',
  text: '#F1ECE4',
  textSecondary: '#C6BDB1',
  textTertiary: '#A39A8E',
  background: '#141210',
  sunken: '#0D0B09',
  surface: '#1E1B18',
  elevated: '#2B2723',
  border: '#403B35',
  borderSecondary: '#322E29',
  success: '#95C285',
  successRgb: '149, 194, 133',
  warning: '#E7BC70',
  warningRgb: '231, 188, 112',
  error: '#EB8D7D',
  errorRgb: '235, 141, 125',
  onAccent: '#1A120C',
  userMessage: '#332E29',
  fill: 'rgba(241, 236, 228, 0.10)',
  fillSecondary: 'rgba(241, 236, 228, 0.15)',
  fillStrong: 'rgba(241, 236, 228, 0.22)',
} as const;

export const designTokens = {
  color: { light, dark },
  graph: { light: graphLight, dark: graphDark },
  typography: {
    body: fontFamily,
    display: displayFamily,
    mono: monoFamily,
    baseSize: 15,
    lineHeight: 1.6,
  },
  spacing: {
    base: 8,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    control: 8,
    surface: 12,
    large: 16,
  },
  width: {
    reading: 760,
    management: 1200,
  },
  motion: {
    duration: { fast: 120, base: 180, slow: 240 },
    easing: 'cubic-bezier(0.2, 0, 0, 1)',
  },
  shadow: {
    xs: '0 1px 2px rgba(35, 31, 27, 0.04)',
    sm: '0 2px 8px rgba(35, 31, 27, 0.05)',
    md: '0 8px 24px rgba(35, 31, 27, 0.07)',
    darkXs: '0 1px 2px rgba(0, 0, 0, 0.28)',
    darkSm: '0 2px 8px rgba(0, 0, 0, 0.34)',
    darkMd: '0 8px 24px rgba(0, 0, 0, 0.42)',
  },
} as const;

export function getCssVariables(theme: DesignTheme): Record<`--${string}`, string> {
  const color = designTokens.color[theme];
  const graph = designTokens.graph[theme];
  const shadow = theme === 'dark'
    ? { xs: designTokens.shadow.darkXs, sm: designTokens.shadow.darkSm, md: designTokens.shadow.darkMd }
    : designTokens.shadow;

  return {
    '--accent': color.accent,
    '--accent-hover': color.accentHover,
    '--accent-active': color.accentActive,
    '--accent-secondary': color.accentSecondary,
    '--accent-text': color.accentText,
    '--accent-rgb': color.accentRgb,
    '--accent-soft': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.17' : '0.07'})`,
    '--accent-soft-strong': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.26' : '0.12'})`,
    '--accent-bg': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.17' : '0.07'})`,
    '--accent-border': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.26' : '0.12'})`,
    '--color-overlay': theme === 'dark' ? 'rgba(0, 0, 0, 0.60)' : 'rgba(0, 0, 0, 0.45)',
    '--gradient-accent': color.accent,
    '--foreground': color.text,
    '--muted': color.sunken,
    '--muted-foreground': color.textSecondary,
    '--background': color.background,
    '--card': color.surface,
    '--border': color.border,
    '--border-secondary': color.borderSecondary,
    '--color-primary': color.accent,
    '--color-primary-rgb': color.accentRgb,
    '--color-accent': color.accent,
    '--color-accent-rgb': color.accentRgb,
    '--color-text': color.text,
    '--color-text-primary': color.text,
    '--color-text-secondary': color.textSecondary,
    '--color-text-tertiary': color.textTertiary,
    '--color-text-placeholder': color.textTertiary,
    '--color-bg-body': color.background,
    '--color-bg-rgb': theme === 'dark' ? '20, 18, 16' : '247, 246, 240',
    '--color-bg-sunken': color.sunken,
    '--color-bg-container': color.surface,
    '--color-bg-container-secondary': color.sunken,
    '--color-bg-elevated': color.elevated,
    '--color-bg-elevated-blur': color.elevated,
    '--color-border': color.border,
    '--color-border-secondary': color.borderSecondary,
    '--color-success': color.success,
    '--color-success-rgb': color.successRgb,
    '--color-error': color.error,
    '--color-error-rgb': color.errorRgb,
    '--color-warning': color.warning,
    '--color-warning-rgb': color.warningRgb,
    '--color-fill': color.fill,
    '--color-fill-secondary': color.fillSecondary,
    '--color-fill-strong': color.fillStrong,
    '--color-bg-hover': color.fill,
    '--color-text-on-accent': color.onAccent,
    '--font-family': designTokens.typography.body,
    '--font-family-display': designTokens.typography.display,
    '--font-family-serif': designTokens.typography.display,
    '--font-family-mono': designTokens.typography.mono,
    '--font-weight-light': '300',
    '--font-weight-regular': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    '--font-weight-bold': '700',
    '--font-size-base': `${designTokens.typography.baseSize}px`,
    '--line-height-base': String(designTokens.typography.lineHeight),
    '--spacing-xs': '4px',
    '--spacing-sm': '8px',
    '--spacing-md': '16px',
    '--spacing-lg': '24px',
    '--spacing-xl': '32px',
    '--spacing-xxl': '48px',
    '--spacing-2xl': '40px',
    '--spacing-3xl': '56px',
    '--spacing-4xl': '72px',
    '--radius-sm': `${designTokens.radius.control}px`,
    '--radius-control': `${designTokens.radius.control}px`,
    '--radius-surface': `${designTokens.radius.surface}px`,
    '--radius-md': `${designTokens.radius.surface}px`,
    '--radius-lg': `${designTokens.radius.large}px`,
    '--radius-xl': `${designTokens.radius.large}px`,
    '--radius-2xl': `${designTokens.radius.large}px`,
    '--radius-3xl': `${designTokens.radius.large}px`,
    '--shadow-xs': shadow.xs,
    '--shadow-sm': shadow.sm,
    '--shadow-md': shadow.md,
    '--shadow-lg': shadow.md,
    '--shadow-xl': shadow.md,
    '--shadow-accent': shadow.sm,
    '--shadow-accent-lg': shadow.md,
    '--shadow-accent-glow': shadow.sm,
    '--shadow-context-menu': shadow.md,
    '--shadow-floating-input': shadow.md,
    '--motion-fast': `${designTokens.motion.duration.fast}ms`,
    '--motion-base': `${designTokens.motion.duration.base}ms`,
    '--motion-slow': `${designTokens.motion.duration.slow}ms`,
    '--motion-ease': designTokens.motion.easing,
    '--ease-out': designTokens.motion.easing,
    '--ease-in-out': designTokens.motion.easing,
    '--ease-spring': designTokens.motion.easing,
    '--ease-soft-spring': designTokens.motion.easing,
    '--ease-smooth': designTokens.motion.easing,
    '--ease-out-expo': designTokens.motion.easing,
    '--dur-instant': 'var(--motion-fast)',
    '--dur-fast': 'var(--motion-fast)',
    '--dur': 'var(--motion-base)',
    '--dur-slow': 'var(--motion-slow)',
    '--dur-page': 'var(--motion-slow)',
    '--transition-page': 'var(--motion-slow) var(--motion-ease)',
    '--user-msg-bg': color.userMessage,
    '--user-msg-accent': color.accent,
    '--msg-bubble-padding': '12px 16px',
    '--content-max': `${designTokens.width.reading}px`,
    '--management-max': `${designTokens.width.management}px`,
    '--page-section-gap': '24px',
    '--card-content-padding': '24px',
    '--color-bg-section': `rgba(${color.accentRgb}, ${theme === 'dark' ? '0.10' : '0.025'})`,
    '--sidebar-width-expanded': '272px',
    '--sidebar-width-collapsed': '0px',
    '--header-height': '56px',
    '--header-blur': 'none',
    '--shadow-subtle-glow': 'none',
    '--gemini-gradient': 'none',
    // Local Graph palette (deep-space blue/violet + neon cyan)
    '--graph-bg': graph.bgEnd,
    '--graph-bg-start': graph.bgStart,
    '--graph-bg-end': graph.bgEnd,
    '--graph-node-fresh': graph.nodeFresh,
    '--graph-node-mid': graph.nodeMid,
    '--graph-node-stale': graph.nodeStale,
    '--graph-node-inactive': graph.nodeInactive,
    '--graph-node-stroke': graph.nodeStroke,
    '--graph-edge-link': graph.edgeLink,
    '--graph-edge-term': graph.edgeTerm,
    '--graph-edge-similar': graph.edgeSimilar,
    '--graph-halo': graph.halo,
    '--graph-halo-rgb': graph.haloRgb,
    '--graph-label': graph.label,
    // hljs syntax highlighting token colors (managed centrally for both themes)
    '--hljs-keyword': theme === 'dark' ? '#E0A07C' : '#d73a49',
    '--hljs-string': theme === 'dark' ? '#9ECE8E' : '#032f62',
    '--hljs-comment': theme === 'dark' ? '#847D6E' : '#6a737d',
    '--hljs-number': theme === 'dark' ? '#E5B567' : '#005cc5',
    '--hljs-title': theme === 'dark' ? '#7FB0D8' : '#6f42c1',
    '--hljs-variable': theme === 'dark' ? '#E08B7C' : '#005cc5',
  };
}

export function applyDesignTokens(theme: DesignTheme): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  root.dataset.theme = theme;
  for (const [name, value] of Object.entries(getCssVariables(theme))) {
    root.style.setProperty(name, value);
  }
}
