# Generated by Django 5.0.14 on 2026-06-25 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0004_pgvector_hnsw_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(help_text='The URL that was crawled. V4.1 KB-V4.1-012: URL length limit 2048.', max_length=2048)),
                ('crawl_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('parsing', 'Parsing'), ('cleaning', 'Cleaning'), ('embedding', 'Embedding'), ('active', 'Active'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn'), ('duplicate_skipped', 'Duplicate Skipped')], default='pending', help_text='Current status in the crawl lifecycle: pending→fetching→parsing→cleaning→embedding→active/failed/withdrawn.', max_length=20)),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA256 hash of cleaned content for dedup detection.', max_length=64)),
                ('copyright_status', models.CharField(choices=[('unknown', 'Unknown'), ('internal_only', 'Internal Only'), ('public_domain', 'Public Domain'), ('restricted', 'Restricted')], default='unknown', help_text='Copyright classification of the crawled content.', max_length=20)),
                ('copyright_disclaimer', models.TextField(blank=True, default='', help_text='Admin-added copyright note for this content.')),
                ('internal_only', models.BooleanField(default=False, help_text='If True, this content is for internal reference only and excluded from external search.')),
                ('robots_txt_allowed', models.BooleanField(default=True, help_text='Whether robots.txt allowed crawling this URL.')),
                ('crawl_delay_seconds', models.IntegerField(default=0, help_text='Crawl-delay from robots.txt (seconds between requests to same domain).')),
                ('title_extracted', models.CharField(blank=True, default='', help_text='Title extracted by trafilatura from the crawled page.', max_length=500)),
                ('raw_content_size', models.IntegerField(default=0, help_text='Size of raw HTML content before cleaning (bytes).')),
                ('cleaned_content_size', models.IntegerField(default=0, help_text='Size of content after bleach cleaning (bytes).')),
                ('error_message', models.TextField(blank=True, default='', help_text="Error message if crawl_status='failed'.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_at', models.DateTimeField(blank=True, help_text='Timestamp when content was actually fetched from the URL.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(blank=True, help_text='Linked knowledge.Document created from crawled content.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_meta', to='knowledge.document')),
                ('submitted_by', models.ForeignKey(help_text='User who submitted this crawl request.', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_crawls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crawler_crawleddocument',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlTaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_domain', models.CharField(help_text='Domain extracted from source_url for per-domain rate limiting.', max_length=255)),
                ('redirect_count', models.IntegerField(default=0, help_text='Number of redirects followed during fetching.')),
                ('final_url', models.URLField(blank=True, default='', help_text='Final URL after all redirects.', max_length=2048)),
                ('user_agent_used', models.CharField(help_text='User-Agent header sent during the crawl request.', max_length=200)),
                ('response_status_code', models.IntegerField(blank=True, help_text='HTTP status code of the final response.', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Total processing time in milliseconds (fetch + clean + embed).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_log', to='crawler.crawleddocument')),
            ],
            options={
                'db_table': 'crawler_crawltasklog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crawleddocument',
            index=models.Index(fields=['source_url'], name='crawler_cra_source__739665_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleddocument',
            index=models.Index(fields=['content_hash'], name='crawler_cra_content_4fc761_idx'),
        ),
        migrations.AddIndex(
            model_name='crawleddocument',
            index=models.Index(fields=['crawl_status'], name='crawler_cra_crawl_s_6270a2_idx'),
        ),
    ]
