# Copyright (c) 2026 Haibo Fang.
# Licensed under the CC BY-NC-SA 4.0 License.
# See LICENSE file in the project root for full license details.

"""Space platform URLs — V6.0 (SPEC.MD §6.1)."""

from django.urls import path

from .views import (
    InviteCodeListCreateView,
    SpaceDetailView,
    SpaceListCreateView,
    SpaceMembersView,
    invite_revoke,
    space_archive,
    space_restore,
    space_transfer,
    space_access_request,
    space_clone,
    discoverable_spaces,
    discovery_highlights,
    space_join,
    space_member_detail,
    space_switch,
)
from .ownership_views import (
    ownership_candidates,
    ownership_detail,
    ownership_transfer_accept,
    ownership_transfer_cancel,
    ownership_transfer_decline,
    ownership_transfer_force,
    ownership_transfer_request,
    legacy_transfer_owner,
    my_pending_ownership_transfers,
)
from .governed_views import (
    creation_request_detail,
    creation_request_mine,
    creation_request_submit,
)
from .taxonomy_views import taxonomy_select
from .deletion_views import (
    workspace_deletion_impact,
    workspace_deletion_request_cancel,
    workspace_deletion_request_confirm,
    workspace_deletion_request_status,
    workspace_deletion_request_submit,
)
from .join_views import (
    access_code_collection,
    access_code_request_submit,
    access_code_revoke,
    access_request_cancel,
    access_request_collection,
    access_request_decision,
    access_request_mine,
    allow_member_invite_toggle_view,
    discoverable_spaces_view,
    global_join_view,
    invitation_collection,
    invitation_revoke,
    join_by_code_view,
    join_code_regenerate_view,
    join_code_view,
    join_policy_switch_view,
)

urlpatterns = [
    path("", SpaceListCreateView.as_view(), name="space-list"),
    path("creation-requests/", creation_request_submit, name="workspace-creation-request-submit"),
    path("creation-requests/mine/", creation_request_mine, name="workspace-creation-request-mine"),
    path("creation-requests/<uuid:request_id>/", creation_request_detail, name="workspace-creation-request-detail"),
    path("creation-requests/<uuid:request_id>/cancel/", creation_request_detail, name="workspace-creation-request-cancel"),
    path("ownership-transfers/pending/", my_pending_ownership_transfers, name="ownership-transfer-pending-list"),
    path("join/", space_join, name="space-join"),
    path("join-by-code/", join_by_code_view, name="space-join-by-code"),
    path("discoverable/", discoverable_spaces_view, name="space-discoverable"),
    path("discovery/highlights/", discovery_highlights, name="space-discovery-highlights"),
    path("taxonomy/<str:kind>/", taxonomy_select, name="space-taxonomy-select"),
    path("access-code-requests/", access_code_request_submit, name="space-access-code-request-submit"),
    path("access-requests/mine/", access_request_mine, name="space-access-request-mine"),
    path("access-requests/<uuid:request_id>/cancel/", access_request_cancel, name="space-access-request-cancel"),
    path("deletion-requests/<uuid:request_id>/", workspace_deletion_request_status, name="workspace-deletion-request-status"),
    path("<uuid:pk>/", SpaceDetailView.as_view(), name="space-detail"),
    path("<uuid:pk>/archive/", space_archive, name="space-archive"),
    path("<uuid:pk>/restore/", space_restore, name="space-restore"),
    path("<uuid:pk>/deletion-impact/", workspace_deletion_impact, name="workspace-deletion-impact"),
    path("<uuid:pk>/deletion-requests/", workspace_deletion_request_submit, name="workspace-deletion-request-submit"),
    path("<uuid:pk>/deletion-requests/<uuid:request_id>/confirm/", workspace_deletion_request_confirm, name="workspace-deletion-request-confirm"),
    path("<uuid:pk>/deletion-requests/<uuid:request_id>/cancel/", workspace_deletion_request_cancel, name="workspace-deletion-request-cancel"),
    path("<uuid:pk>/transfer/", space_transfer, name="space-transfer"),
    path("<uuid:pk>/clone/", space_clone, name="space-clone"),
    path("<uuid:pk>/ownership/", ownership_detail, name="ownership-detail"),
    path("<uuid:pk>/ownership-candidates/", ownership_candidates, name="ownership-candidates"),
    path("<uuid:pk>/ownership-transfers/", ownership_transfer_request, name="ownership-transfer-request"),
    path("<uuid:pk>/transfer-owner/", legacy_transfer_owner, name="space-transfer-owner"),
    path("<uuid:pk>/ownership-transfers/force/", ownership_transfer_force, name="ownership-transfer-force"),
    path("<uuid:pk>/ownership-transfers/<uuid:transfer_id>/accept/", ownership_transfer_accept, name="ownership-transfer-accept"),
    path("<uuid:pk>/ownership-transfers/<uuid:transfer_id>/decline/", ownership_transfer_decline, name="ownership-transfer-decline"),
    path("<uuid:pk>/ownership-transfers/<uuid:transfer_id>/cancel/", ownership_transfer_cancel, name="ownership-transfer-cancel"),
    path("<uuid:space_id>/access-requests/", access_request_collection, name="space-access-request"),
    path("<uuid:space_id>/access-requests/<uuid:request_id>/<str:action>/", access_request_decision, name="space-access-request-decision"),
    path("<uuid:space_id>/access-codes/", access_code_collection, name="space-access-code-list"),
    path("<uuid:space_id>/access-codes/<uuid:code_id>/revoke/", access_code_revoke, name="space-access-code-revoke"),
    path("<uuid:space_id>/invitations/", invitation_collection, name="space-invitation-list"),
    path("<uuid:space_id>/invitations/<uuid:invitation_id>/revoke/", invitation_revoke, name="space-invitation-revoke"),
    path("<uuid:space_id>/join-code/", join_code_view, name="space-join-code"),
    path("<uuid:space_id>/join-code/regenerate/", join_code_regenerate_view, name="space-join-code-regenerate"),
    path("<uuid:space_id>/join/", global_join_view, name="space-global-join"),
    path("<uuid:space_id>/join-policy/switch/", join_policy_switch_view, name="space-join-policy-switch"),
    path("<uuid:space_id>/allow-member-invite/", allow_member_invite_toggle_view, name="space-allow-member-invite"),
    path("<uuid:pk>/switch/", space_switch, name="space-switch"),
    path("<uuid:pk>/members/", SpaceMembersView.as_view(), name="space-members"),
    path("<uuid:pk>/members/<uuid:user_id>/", space_member_detail, name="space-member-detail"),
    path("<uuid:pk>/invites/", InviteCodeListCreateView.as_view(), name="space-invite-list"),
    path("<uuid:pk>/invites/<uuid:invite_id>/revoke/", invite_revoke, name="space-invite-revoke"),
]
