# Generated by Django 5.0.14 on 2026-07-02 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'type', 'is_read', 'created_at'], name='notif_rec_type_read_cr_idx'),
        ),
    ]
