# Generated by Django 5.0.14 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0003_phase9a_account_security")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deactivated_users",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivation_reason_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
