# Generated by Django 5.0.14 on 2026-07-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0019_knowledgespace_review_policy'),
        ('users', '0005_test_principal_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='spaces.businessline'),
        ),
    ]
