# Generated by Django 5.0.14 on 2026-06-29 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spaces_businessline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spaces_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('language', models.CharField(default='en', max_length=8)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('business_line', 'Business Line Internal'), ('organization', 'Organization Shared'), ('public_demo', 'Public Demo')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='spaces.businessline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='spaces.organization')),
            ],
            options={
                'db_table': 'spaces_knowledgespace',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hex of the access code', max_length=64, unique=True)),
                ('code_prefix', models.CharField(blank=True, default='', help_text="Display prefix, e.g. 'AUD-'", max_length=12)),
                ('role', models.CharField(choices=[('owner', 'Space Owner'), ('knowledge_admin', 'Knowledge Admin'), ('reviewer', 'Reviewer'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('used_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_codes_created', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='spaces.knowledgespace')),
            ],
            options={
                'db_table': 'spaces_invitecode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businessline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_lines', to='spaces.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='businessline',
            unique_together={('organization', 'code')},
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Space Owner'), ('knowledge_admin', 'Knowledge Admin'), ('reviewer', 'Reviewer'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spaces.knowledgespace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spaces_spacemembership',
                'ordering': ['-last_accessed_at', '-created_at'],
                'unique_together': {('space', 'user')},
            },
        ),
    ]
