# Generated by Django 5.0.14 on 2026-06-30 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_organizationmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistrationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hex of the admin code', max_length=64, unique=True)),
                ('code_prefix', models.CharField(blank=True, default='', max_length=12)),
                ('grants_role', models.CharField(choices=[('org_admin', 'Organization Admin'), ('business_admin', 'Business Admin')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('used_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_line', models.ForeignKey(blank=True, help_text='Required for business_admin; ignored for org_admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_codes', to='spaces.businessline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_codes_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_codes', to='spaces.organization')),
            ],
            options={
                'db_table': 'spaces_adminregistrationcode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceEmailInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Space Owner'), ('knowledge_admin', 'Knowledge Admin'), ('reviewer', 'Reviewer'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_invites', to='spaces.knowledgespace')),
            ],
            options={
                'db_table': 'spaces_spaceemailinvite',
                'ordering': ['-created_at'],
                'unique_together': {('space', 'email')},
            },
        ),
    ]
