# Generated by Django 5.0.14 on 2026-07-12 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_spaceaccessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_policies', to='spaces.organization')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='governance_policies', to='spaces.knowledgespace')),
            ],
            options={
                'db_table': 'spaces_governancepolicy',
                'ordering': ['-revision', '-created_at'],
            },
        ),
    ]
