# Generated by Django 5.0.14 on 2026-07-12 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_governancepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=40)),
                ('model_id', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spaces_modelprofile',
            },
        ),
    ]
