# Generated by Django 5.0.14 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0007_modelprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
