# Generated by Django 5.0.14 on 2026-07-18

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0008_organizationmembership_effectiveness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgespace",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OwnershipTransfer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mode", models.CharField(choices=[("voluntary", "Voluntary"), ("forced", "Forced"), ("offboarding", "Offboarding")], max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("declined", "Declined"), ("cancelled", "Cancelled"), ("expired", "Expired"), ("invalidated", "Invalidated")], max_length=16)),
                ("expected_ownership_version", models.PositiveIntegerField()),
                ("reason_code", models.CharField(max_length=64)),
                ("reason_note", models.CharField(blank=True, default="", max_length=500)),
                ("idempotency_key", models.UUIDField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ownership_transfers_accepted", to=settings.AUTH_USER_MODEL)),
                ("from_owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ownership_transfers_from", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ownership_transfers_requested", to=settings.AUTH_USER_MODEL)),
                ("space", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ownership_transfers", to="spaces.knowledgespace")),
                ("to_owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ownership_transfers_to", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "spaces_ownershiptransfer"},
        ),
        migrations.AddConstraint(
            model_name="ownershiptransfer",
            constraint=models.UniqueConstraint(fields=("space",), condition=Q(status="pending"), name="spaces_one_pending_owner_transfer"),
        ),
        migrations.AddConstraint(
            model_name="ownershiptransfer",
            constraint=models.UniqueConstraint(fields=("requested_by", "idempotency_key"), name="spaces_owner_transfer_request_key"),
        ),
        migrations.AddConstraint(
            model_name="ownershiptransfer",
            constraint=models.CheckConstraint(
                check=~Q(from_owner=models.F("to_owner")), name="spaces_owner_transfer_distinct"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershiptransfer",
            constraint=models.CheckConstraint(
                check=~Q(status="completed") | Q(completed_at__isnull=False),
                name="spaces_owner_transfer_completed_timestamp",
            ),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="ownership_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
