# Generated by Django 5.0.14 on 2026-07-18

import django.db.models.deletion
import re
import unicodedata
import uuid
from django.conf import settings
from django.db import migrations, models


def _normalize_locator_code(value):
    code = unicodedata.normalize("NFKC", value or "").strip().lower()
    code = re.sub(r"[\s_]+", "-", code)
    code = re.sub(r"[^a-z0-9-]", "-", code)
    code = re.sub(r"-+", "-", code).strip("-")
    if not re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,118}[a-z0-9])?", code):
        raise RuntimeError("workspace_locator_backfill_invalid_code")
    return code


def backfill_workspace_locators(apps, schema_editor):
    """Reserve every historical live locator without guessing or truncation."""

    KnowledgeSpace = apps.get_model("spaces", "KnowledgeSpace")
    WorkspaceLocatorReservation = apps.get_model(
        "spaces", "WorkspaceLocatorReservation"
    )
    seen = set()
    batch = []
    spaces = KnowledgeSpace.objects.select_related("organization").order_by("pk")
    for space in spaces.iterator(chunk_size=500):
        normalized_code = _normalize_locator_code(space.code)
        normalized_org = _normalize_locator_code(space.organization.slug)
        normalized_locator = f"{normalized_org}/{normalized_code}"
        key = (space.organization_id, normalized_code)
        if key in seen or len(normalized_locator) > 180:
            raise RuntimeError("workspace_locator_backfill_collision")
        seen.add(key)
        batch.append(
            WorkspaceLocatorReservation(
                organization_id=space.organization_id,
                normalized_code=normalized_code,
                normalized_locator=normalized_locator,
                state="live",
                live_space_id=space.pk,
            )
        )
        if len(batch) == 500:
            WorkspaceLocatorReservation.objects.bulk_create(batch)
            batch = []
    if batch:
        WorkspaceLocatorReservation.objects.bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0012_internal_beta_taxonomy"),
        ("users", "0005_test_principal_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgespace",
            name="dependency_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="lifecycle_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="provisioning_status",
            field=models.CharField(
                choices=[
                    ("provisioning", "Provisioning"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GovernedActionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action_type", models.CharField(choices=[("workspace_create", "Workspace create"), ("workspace_permanent_delete", "Workspace permanent delete")], max_length=40)),
                ("requester_uuid", models.UUIDField(db_index=True)),
                ("scope_type", models.CharField(default="platform", max_length=40)),
                ("scope_uuid", models.UUIDField(blank=True, null=True)),
                ("target_space_uuid", models.UUIDField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("rejected", "Rejected"), ("cancelled", "Cancelled"), ("expired", "Expired"), ("scheduled", "Scheduled"), ("executing", "Executing"), ("failed", "Failed"), ("invalidated", "Invalidated")], default="pending", max_length=20)),
                ("idempotency_key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("request_version", models.PositiveBigIntegerField(default=1)),
                ("impact_revision", models.PositiveBigIntegerField(default=0)),
                ("impact_version", models.CharField(blank=True, default="", max_length=64)),
                ("impact_expires_at", models.DateTimeField(blank=True, null=True)),
                ("impact_snapshot", models.JSONField(blank=True, default=dict)),
                ("reviewer_uuid", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, default="", max_length=64)),
                ("reason_text", models.CharField(blank=True, default="", max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result_uuid", models.UUIDField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_line", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="governed_requests", to="spaces.businessline")),
                ("organization", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="governed_requests", to="spaces.organization")),
                ("requester", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="governed_requests_submitted", to=settings.AUTH_USER_MODEL)),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="governed_requests_reviewed", to=settings.AUTH_USER_MODEL)),
                ("target_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="governed_requests", to="spaces.knowledgespace")),
            ],
            options={"db_table": "spaces_governedactionrequest", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="GovernedActionOutbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=80)),
                ("payload_version", models.PositiveSmallIntegerField(default=1)),
                ("transition_version", models.PositiveBigIntegerField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("state", models.CharField(choices=[("pending", "Pending"), ("delivered", "Delivered"), ("failed", "Failed")], default="pending", max_length=12)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("recipient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="governed_outbox_events", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outbox_events", to="spaces.governedactionrequest")),
            ],
            options={"db_table": "spaces_governedactionoutbox"},
        ),
        migrations.CreateModel(
            name="WorkspaceCreateRequestDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("normalized_name", models.CharField(max_length=200)),
                ("normalized_code", models.CharField(max_length=120)),
                ("purpose", models.TextField(max_length=1000)),
                ("requested_visibility", models.CharField(default="private", max_length=20)),
                ("work_group_id", models.UUIDField()),
                ("office_location_ids", models.JSONField(default=list)),
                ("template_version_id", models.UUIDField(blank=True, null=True)),
                ("created_space_uuid", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="create_request_details", to="spaces.businessline")),
                ("request", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="create_detail", to="spaces.governedactionrequest")),
            ],
            options={"db_table": "spaces_workspacecreaterequestdetail"},
        ),
        migrations.CreateModel(
            name="WorkspaceCreationPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("retired", "Retired")], default="draft", max_length=12)),
                ("audience", models.CharField(choices=[("registered_beta", "Registered beta"), ("authoritative_members", "Authoritative members")], default="registered_beta", max_length=32)),
                ("review_route", models.CharField(choices=[("platform", "Platform"), ("nearest_scope", "Nearest scope")], default="platform", max_length=20)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("reviewer_separation_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("business_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workspace_creation_policies", to="spaces.businessline")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspace_creation_policies_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "spaces_workspacecreationpolicy", "ordering": ["business_line_id", "-revision"]},
        ),
        migrations.CreateModel(
            name="WorkspaceDeletionRequestDetail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("locator", models.CharField(max_length=180)),
                ("expected_lifecycle_version", models.PositiveBigIntegerField()),
                ("expected_ownership_version", models.PositiveBigIntegerField()),
                ("archived_at", models.DateTimeField()),
                ("purge_not_before", models.DateTimeField(blank=True, null=True)),
                ("confirmation_digest", models.CharField(blank=True, default="", max_length=64)),
                ("tombstone_uuid", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="delete_detail", to="spaces.governedactionrequest")),
            ],
            options={"db_table": "spaces_workspacedeletionrequestdetail"},
        ),
        migrations.CreateModel(
            name="WorkspaceLocatorReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("normalized_code", models.CharField(max_length=120)),
                ("normalized_locator", models.CharField(blank=True, default="", max_length=180)),
                ("state", models.CharField(choices=[("request_reserved", "Request reserved"), ("live", "Live"), ("tombstoned", "Tombstoned"), ("released", "Released")], max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active_request", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reserved_locator", to="spaces.governedactionrequest")),
                ("live_space", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="locator_reservation", to="spaces.knowledgespace")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="locator_reservations", to="spaces.organization")),
            ],
            options={"db_table": "spaces_workspacelocatorreservation"},
        ),
        migrations.RunPython(
            backfill_workspace_locators,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="governedactionrequest",
            name="locator_reservation",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="governed_requests", to="spaces.workspacelocatorreservation"),
        ),
        migrations.CreateModel(
            name="WriteIdempotencyRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_uuid", models.UUIDField()),
                ("operation_code", models.CharField(max_length=80)),
                ("key", models.UUIDField()),
                ("request_digest", models.CharField(max_length=64)),
                ("target_uuid", models.UUIDField(blank=True, null=True)),
                ("request_uuid", models.UUIDField(blank=True, null=True)),
                ("disposition", models.CharField(choices=[("in_progress", "In progress"), ("completed", "Completed"), ("failed", "Failed")], default="in_progress", max_length=20)),
                ("result_reference", models.UUIDField(blank=True, null=True)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_schema_version", models.PositiveSmallIntegerField(default=1)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("failure_code", models.CharField(blank=True, default="", max_length=80)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "spaces_writeidempotencyrecord",
                "indexes": [models.Index(fields=["expires_at", "disposition"], name="spaces_writ_expires_f11bfd_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="writeidempotencyrecord",
            constraint=models.UniqueConstraint(fields=("actor_uuid", "operation_code", "key"), name="spaces_write_idempotency_actor_operation_key"),
        ),
        migrations.AddConstraint(
            model_name="writeidempotencyrecord",
            constraint=models.CheckConstraint(check=models.Q(("request_digest__regex", "^[0-9a-f]{64}$")), name="spaces_write_idempotency_digest_shape"),
        ),
        migrations.AddIndex(
            model_name="governedactionoutbox",
            index=models.Index(fields=["state", "next_attempt_at", "created_at"], name="spaces_gove_state_bf2694_idx"),
        ),
        migrations.AddConstraint(
            model_name="governedactionoutbox",
            constraint=models.UniqueConstraint(fields=("request", "event_type", "recipient", "transition_version"), name="spaces_governed_outbox_transition_unique"),
        ),
        migrations.AddConstraint(
            model_name="workspacecreaterequestdetail",
            constraint=models.UniqueConstraint(fields=("request",), name="spaces_create_detail_request_unique"),
        ),
        migrations.AddConstraint(
            model_name="workspacecreationpolicy",
            constraint=models.UniqueConstraint(fields=("business_line", "revision"), name="spaces_creation_policy_business_revision"),
        ),
        migrations.AddConstraint(
            model_name="workspacecreationpolicy",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "active")), fields=("business_line",), name="spaces_one_active_creation_policy"),
        ),
        migrations.AddConstraint(
            model_name="workspacecreationpolicy",
            constraint=models.CheckConstraint(check=models.Q(models.Q(("effective_from__isnull", False), ("effective_until__isnull", False), _negated=True), ("effective_until__gte", models.F("effective_from")), _connector="OR"), name="spaces_creation_policy_effective_order"),
        ),
        migrations.AddIndex(
            model_name="governedactionrequest",
            index=models.Index(fields=["action_type", "status", "created_at"], name="spaces_gove_action__acc86c_idx"),
        ),
        migrations.AddIndex(
            model_name="governedactionrequest",
            index=models.Index(fields=["requester_uuid", "status", "created_at"], name="spaces_gove_request_6dc304_idx"),
        ),
        migrations.AddConstraint(
            model_name="governedactionrequest",
            constraint=models.UniqueConstraint(fields=("requester_uuid", "action_type", "idempotency_key"), name="spaces_governed_request_submit_key"),
        ),
        migrations.AddConstraint(
            model_name="governedactionrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("action_type", "workspace_permanent_delete"), ("status__in", ("pending", "scheduled", "executing", "failed"))), fields=("target_space",), name="spaces_one_live_delete_request"),
        ),
        migrations.AddConstraint(
            model_name="governedactionrequest",
            constraint=models.CheckConstraint(check=models.Q(("request_digest__regex", "^[0-9a-f]{64}$")), name="spaces_governed_request_digest_shape"),
        ),
        migrations.AddConstraint(
            model_name="governedactionrequest",
            constraint=models.CheckConstraint(check=models.Q(models.Q(("action_type", "workspace_permanent_delete"), _negated=True), ("target_space_uuid__isnull", False), _connector="OR"), name="spaces_delete_has_target_snapshot"),
        ),
        migrations.AddIndex(
            model_name="workspacelocatorreservation",
            index=models.Index(fields=["organization", "state", "normalized_code"], name="spaces_work_organiz_d02ed9_idx"),
        ),
        migrations.AddConstraint(
            model_name="workspacelocatorreservation",
            constraint=models.UniqueConstraint(fields=("organization", "normalized_code"), name="spaces_locator_org_code_unique"),
        ),
        migrations.AddConstraint(
            model_name="workspacelocatorreservation",
            constraint=models.CheckConstraint(check=models.Q(models.Q(("state", "live"), _negated=True), ("live_space__isnull", False), _connector="OR"), name="spaces_locator_live_has_space"),
        ),
    ]
