# Generated by Django 5.0.14 on 2026-07-18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


REGISTRY_ROWS = (
    ("users.User", "default_space", "retained_evidence", "", 7, 5, "spaces.0016_workspace_deletion_stage_c"),
    ("knowledge.DocumentCategory", "space", "eligible_content", "child_categories", 13, 10, "knowledge.0011_workspace_retention_contract"),
    ("knowledge.DocumentChunk", "space", "eligible_content", "", 12, 20, "knowledge.0011_workspace_retention_contract"),
    ("knowledge.Document", "space", "eligible_content", "", 12, 30, "knowledge.0011_workspace_retention_contract"),
    ("knowledge.IngestionJob", "space", "retained_evidence", "open_tasks", 13, 40, "knowledge.0011_workspace_retention_contract"),
    ("knowledge.BatchImportResultRecord", "space", "retained_evidence", "open_tasks", 13, 50, "knowledge.0011_workspace_retention_contract"),
    ("chat.ConversationShare", "session__space", "credential", "active_shares", 13, 60, "chat.0018_workspace_retention_contract"),
    ("chat.Citation", "space", "eligible_content", "", 12, 70, "chat.0018_workspace_retention_contract"),
    ("chat.Message", "space", "eligible_content", "", 12, 80, "chat.0018_workspace_retention_contract"),
    ("chat.ChatTurn", "space", "eligible_content", "active_chat_execution", 12, 90, "chat.0018_workspace_retention_contract"),
    ("chat.ChatSession", "space", "eligible_content", "", 12, 100, "chat.0018_workspace_retention_contract"),
    ("chat.Feedback", "space", "retained_evidence", "open_tasks", 13, 110, "chat.0018_workspace_retention_contract"),
    ("chat.FeedbackReviewEvent", "space", "retained_evidence", "", 13, 120, "chat.0018_workspace_retention_contract"),
    ("chat.KnowledgeGapTicket", "space", "retained_evidence", "open_tasks", 13, 130, "chat.0018_workspace_retention_contract"),
    ("chat.ComplianceExportJob", "space", "retained_evidence", "open_tasks", 13, 140, "chat.0018_workspace_retention_contract"),
    ("chat.ModelInvocation", "space", "retained_evidence", "", 13, 150, "chat.0018_workspace_retention_contract"),
    ("scenario_templates.ScenarioTemplateApplication", "space", "retained_evidence", "", 13, 160, "scenario_templates.0007_workspace_retention_contract"),
    ("audit.AuditLog", "space_id", "retained_evidence", "", 15, 170, "audit.0015_workspace_retention_contract"),
    ("spaces.SpaceMembership", "space", "credential", "", 8, 180, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.InviteCode", "space", "credential", "", 10, 190, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.SpaceEmailInvite", "space", "credential", "", 10, 200, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.SpaceAccessCode", "space", "credential", "", 10, 210, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.SpaceInvitation", "space", "credential", "", 10, 220, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.SpaceAccessRequest", "space", "credential", "", 10, 230, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspaceUsageDaily", "space", "personalization", "", 13, 240, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.KnowledgeSpaceOfficeLocation", "space", "personalization", "", 13, 245, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspaceUsageSummary", "space", "personalization", "", 13, 250, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.GovernancePolicy", "space", "retained_evidence", "", 13, 260, "spaces.0016_workspace_deletion_stage_c"),
    ("spaces.OwnershipTransfer", "space", "retained_evidence", "ownership_transition_pending", 9, 270, "spaces.0016_workspace_deletion_stage_c"),
    ("spaces.GovernedActionRequest", "target_space", "retained_evidence", "", 11, 280, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspaceRetentionHold", "space", "retained_evidence", "retention_hold", 13, 290, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspaceLocatorReservation", "live_space", "retained_evidence", "", 4, 300, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspaceTombstone", "original_space_uuid", "retained_evidence", "", 14, 310, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspacePurgeJob", "request", "retained_evidence", "open_tasks", 14, 320, "spaces.0015_workspace_deletion_stage_a"),
    ("spaces.WorkspacePurgeCheckpoint", "job", "retained_evidence", "open_tasks", 14, 330, "spaces.0015_workspace_deletion_stage_a"),
    ("notifications.Notification", "resource_uuid", "retained_evidence", "", 15, 340, "notifications.0003_actionable_notification_contract"),
)


def seed_purge_registry(apps, schema_editor):
    Registry = apps.get_model("spaces", "WorkspacePurgeDependency")
    ready_owners = {
        "spaces.0015_workspace_deletion_stage_a",
        "notifications.0003_actionable_notification_contract",
    }
    for model_label, space_field, disposition, blocker, lock_order, purge_order, owner in REGISTRY_ROWS:
        Registry.objects.update_or_create(
            model_label=model_label,
            space_field=space_field,
            defaults={
                "disposition": disposition,
                "blocker_code": blocker,
                "lock_order": lock_order,
                "purge_order": purge_order,
                "snapshot_fields": ["space_uuid", "organization_uuid", "tombstone_id"] if disposition == "retained_evidence" else [],
                "scrub_fields": [],
                "migration_owner": owner,
                "registration_state": "ready" if owner in ready_owners else "pending",
                "schema_revision": 1,
                "required": True,
                "active": True,
            },
        )


def backfill_stage_a_snapshots(apps, schema_editor):
    KnowledgeSpace = apps.get_model("spaces", "KnowledgeSpace")
    GovernancePolicy = apps.get_model("spaces", "GovernancePolicy")

    # Preserve the best durable lifecycle evidence available for workspaces
    # archived before the v3 timestamp was introduced.  Do not invent a
    # retention deadline; the governed deletion flow computes it from the
    # captured policy revision.
    for space in KnowledgeSpace.objects.filter(
        status="archived",
        archived_at__isnull=True,
    ).only("pk", "updated_at"):
        KnowledgeSpace.objects.filter(pk=space.pk).update(
            archived_at=space.updated_at,
        )

    space_ids = list(
        GovernancePolicy.objects.exclude(space_id__isnull=True).values_list(
            "space_id", flat=True
        )
    )
    space_organizations = dict(
        KnowledgeSpace.objects.filter(pk__in=space_ids).values_list(
            "pk", "organization_id"
        )
    )
    for policy in GovernancePolicy.objects.all().only(
        "pk", "space_id", "organization_id"
    ):
        GovernancePolicy.objects.filter(pk=policy.pk).update(
            space_uuid=policy.space_id,
            organization_uuid=(
                policy.organization_id
                or space_organizations.get(policy.space_id)
            ),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0014_workspace_join_v2"),
        ("notifications", "0003_actionable_notification_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspacePurgeJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("failed", "Failed"), ("completed", "Completed")], default="queued", max_length=12)),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("lease_generation", models.PositiveBigIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("session_fence_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("request_version_snapshot", models.PositiveBigIntegerField(default=0)),
                ("lifecycle_version_snapshot", models.PositiveBigIntegerField(default=0)),
                ("ownership_version_snapshot", models.PositiveBigIntegerField(default=0)),
                ("impact_version_snapshot", models.CharField(blank=True, default="", max_length=64)),
                ("retention_not_before", models.DateTimeField(blank=True, null=True)),
                ("manifest_version", models.PositiveBigIntegerField(default=0)),
                ("manifest_digest", models.CharField(blank=True, default="", max_length=64)),
                ("failure_code", models.CharField(blank=True, default="", max_length=80)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="purge_job", to="spaces.governedactionrequest")),
            ],
            options={
                "db_table": "spaces_workspacepurgejob",
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(("manifest_digest", ""), ("manifest_version", 0)),
                            models.Q(("manifest_digest__regex", "^[0-9a-f]{64}$"), ("manifest_version__gte", 1)),
                            _connector="OR",
                        ),
                        name="spaces_purge_job_manifest_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspacePurgeCheckpoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("store_code", models.CharField(choices=[("database", "Database"), ("blob", "Blob"), ("search", "Search"), ("vector", "Vector"), ("replay", "Replay")], max_length=20)),
                ("batch_key", models.CharField(max_length=160)),
                ("expected_digest", models.CharField(blank=True, default="", max_length=64)),
                ("acknowledged_digest", models.CharField(blank=True, default="", max_length=64)),
                ("item_count", models.PositiveBigIntegerField(default=0)),
                ("byte_count", models.PositiveBigIntegerField(default=0)),
                ("last_cursor", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("acked", "Acked"), ("failed", "Failed")], default="pending", max_length=12)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_generation", models.PositiveBigIntegerField(default=0)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checkpoints", to="spaces.workspacepurgejob")),
            ],
            options={"db_table": "spaces_workspacepurgecheckpoint"},
        ),
        migrations.CreateModel(
            name="WorkspaceTombstone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_space_uuid", models.UUIDField(unique=True)),
                ("organization_uuid", models.UUIDField()),
                ("request_uuid", models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ("locator_digest", models.CharField(max_length=64)),
                ("normalized_locator", models.CharField(max_length=180)),
                ("normalized_org_slug", models.CharField(blank=True, default="", max_length=120)),
                ("normalized_space_code", models.CharField(blank=True, default="", max_length=120)),
                ("archived_at", models.DateTimeField()),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("final_manifest_digest", models.CharField(blank=True, default="", max_length=64)),
                ("manifest_version", models.PositiveBigIntegerField(default=0)),
                ("retention_flags", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("locator_reservation", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="tombstone_marker", to="spaces.workspacelocatorreservation")),
                ("request", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="tombstone_marker", to="spaces.governedactionrequest")),
            ],
            options={"db_table": "spaces_workspacetombstone"},
        ),
        migrations.CreateModel(
            name="WorkspacePurgeDependency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_label", models.CharField(max_length=160)),
                ("space_field", models.CharField(blank=True, default="", max_length=80)),
                ("disposition", models.CharField(choices=[("eligible_content", "Eligible content"), ("retained_evidence", "Retained evidence"), ("credential", "Credential"), ("personalization", "Personalization"), ("blocker", "Blocker")], max_length=24)),
                ("blocker_code", models.CharField(blank=True, default="", max_length=64)),
                ("lock_order", models.PositiveSmallIntegerField()),
                ("purge_order", models.PositiveSmallIntegerField()),
                ("snapshot_fields", models.JSONField(blank=True, default=list)),
                ("scrub_fields", models.JSONField(blank=True, default=list)),
                ("migration_owner", models.CharField(max_length=160)),
                ("registration_state", models.CharField(choices=[("pending", "Pending"), ("ready", "Ready")], default="pending", max_length=12)),
                ("schema_revision", models.PositiveBigIntegerField(default=1)),
                ("required", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "spaces_workspacepurgedependency",
                "ordering": ["purge_order", "model_label", "space_field"],
                "constraints": [
                    models.UniqueConstraint(fields=("model_label", "space_field"), name="spaces_purge_dependency_model_field"),
                    models.CheckConstraint(check=models.Q(("lock_order__gte", 1), ("purge_order__gte", 1)), name="spaces_purge_dependency_order_positive"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceRetentionHold",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("space_uuid", models.UUIDField()),
                ("organization_uuid", models.UUIDField()),
                ("locator_digest", models.CharField(max_length=64)),
                ("hold_type", models.CharField(choices=[("legal", "Legal"), ("audit", "Audit"), ("investigation", "Investigation"), ("backup", "Backup"), ("business_record", "Business record")], max_length=24)),
                ("status", models.CharField(choices=[("active", "Active"), ("released", "Released"), ("expired", "Expired")], default="active", max_length=12)),
                ("reason_code", models.CharField(max_length=64)),
                ("policy_version", models.PositiveBigIntegerField(default=1)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("effective_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("release_not_before", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_uuid", models.UUIDField(blank=True, editable=False, null=True)),
                ("released_by_uuid", models.UUIDField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspace_retention_holds_created", to=settings.AUTH_USER_MODEL)),
                ("released_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workspace_retention_holds_released", to=settings.AUTH_USER_MODEL)),
                ("space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retention_holds", to="spaces.knowledgespace")),
                ("tombstone", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retention_holds", to="spaces.workspacetombstone")),
            ],
            options={
                "db_table": "spaces_workspaceretentionhold",
                "indexes": [models.Index(fields=["space_uuid", "status", "hold_type"], name="spaces_hold_space_status")],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("status", "active")), fields=("space", "hold_type"), name="spaces_one_active_retention_hold"),
                    models.CheckConstraint(check=models.Q(("locator_digest__regex", "^[0-9a-f]{64}$")), name="spaces_retention_hold_locator_shape"),
                    models.CheckConstraint(check=models.Q(models.Q(("status", "active"), _negated=True), models.Q(("space__isnull", False), ("released_at__isnull", True)), _connector="OR"), name="spaces_active_hold_live_space"),
                    models.CheckConstraint(check=models.Q(models.Q(("status", "released"), _negated=True), ("released_at__isnull", False), _connector="OR"), name="spaces_released_hold_timestamp"),
                ],
            },
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="purge_fence_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="retention_policy_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="retention_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="storage_manifest_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="storage_manifest_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgespace",
            name="storage_manifest_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workspacedeletionrequestdetail",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacedeletionrequestdetail",
            name="expected_dependency_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workspacedeletionrequestdetail",
            name="purge_job_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacedeletionrequestdetail",
            name="retention_policy_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="workspacedeletionrequestdetail",
            name="storage_manifest_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="workspacedeletionrequestdetail",
            name="storage_manifest_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="governancepolicy",
            name="organization_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="governancepolicy",
            name="space_uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="governancepolicy",
            name="tombstone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="governance_policies",
                to="spaces.workspacetombstone",
            ),
        ),
        migrations.RunPython(
            backfill_stage_a_snapshots,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="governancepolicy",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="governance_policies",
                to="spaces.knowledgespace",
            ),
        ),
        migrations.AddField(
            model_name="workspacelocatorreservation",
            name="tombstone",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tombstone_reservation", to="spaces.workspacetombstone"),
        ),
        migrations.AddConstraint(
            model_name="workspacepurgecheckpoint",
            constraint=models.UniqueConstraint(fields=("job", "store_code", "batch_key"), name="spaces_purge_checkpoint_store_batch_unique"),
        ),
        migrations.AddConstraint(
            model_name="workspacetombstone",
            constraint=models.CheckConstraint(check=models.Q(("locator_digest__regex", "^[0-9a-f]{64}$")), name="spaces_tombstone_locator_digest_shape"),
        ),
        migrations.AddConstraint(
            model_name="knowledgespace",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("storage_manifest_digest", ""),
                        ("storage_manifest_version", 0),
                    ),
                    models.Q(
                        ("storage_manifest_digest__regex", "^[0-9a-f]{64}$"),
                        ("storage_manifest_generated_at__isnull", False),
                        ("storage_manifest_version__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="spaces_storage_manifest_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacedeletionrequestdetail",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("storage_manifest_digest", ""),
                        ("storage_manifest_version", 0),
                    ),
                    models.Q(
                        ("storage_manifest_digest__regex", "^[0-9a-f]{64}$"),
                        ("storage_manifest_version__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="spaces_delete_detail_manifest_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacepurgecheckpoint",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("store_code__in", ["database", "blob", "search", "vector", "replay"])
                ),
                name="spaces_purge_checkpoint_store_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacetombstone",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("final_manifest_digest", ""),
                        ("manifest_version", 0),
                    ),
                    models.Q(
                        ("final_manifest_digest__regex", "^[0-9a-f]{64}$"),
                        ("manifest_version__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="spaces_tombstone_manifest_shape",
            ),
        ),
        migrations.RunPython(
            seed_purge_registry,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
