# Generated by Django 5.0.14 on 2026-07-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0016_workspace_deletion_stage_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='default_language',
            field=models.CharField(choices=[('auto', 'Auto-detect'), ('zh', 'Chinese'), ('en', 'English')], default='auto', max_length=8),
        ),
    ]
