# Generated by Django 5.0.14 on 2026-07-22 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0017_knowledgespace_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='allow_member_invite',
            field=models.BooleanField(default=True, help_text='Whether non-owner members can invite new users.'),
        ),
        migrations.AddField(
            model_name='knowledgespace',
            name='join_code',
            field=models.CharField(blank=True, help_text='Human-readable unique join code. Required when join_policy=access_code.', max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='knowledgespace',
            name='join_code_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgespace',
            name='join_policy',
            field=models.CharField(choices=[('access_code', 'Access Code'), ('global', 'Global Visible')], default='access_code', help_text='Determines how new users discover and join this workspace.', max_length=20),
        ),
        migrations.AddField(
            model_name='workspacecreaterequestdetail',
            name='requested_join_code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='workspacecreaterequestdetail',
            name='requested_join_policy',
            field=models.CharField(default='access_code', max_length=20),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='source_kind',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('manual', 'Manual'), ('access_request', 'Access Request'), ('invitation', 'Invitation'), ('ownership', 'Ownership'), ('join_code', 'Join Code'), ('discovery', 'Discovery')], default='legacy', max_length=20),
        ),
        migrations.AddIndex(
            model_name='knowledgespace',
            index=models.Index(fields=['join_policy', 'status'], name='spaces_join_policy_status'),
        ),
        migrations.AddConstraint(
            model_name='knowledgespace',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('join_policy', 'access_code'), _negated=True), ('join_code__isnull', False), _connector='OR'), name='spaces_join_code_required_for_access_code'),
        ),
    ]
