# Generated by Django 5.0.14 on 2026-07-26 13:48

from django.db import migrations, models


def _backfill_direct_publish(apps, schema_editor):
    """Spec §3.1: existing spaces keep current behavior (no review gate);
    only newly created spaces default to require_review."""
    KnowledgeSpace = apps.get_model("spaces", "KnowledgeSpace")
    KnowledgeSpace.objects.all().update(review_policy="direct_publish")


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0018_knowledgespace_join_and_invite_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='review_policy',
            field=models.CharField(choices=[('direct_publish', 'Direct Publish'), ('require_review', 'Require Review')], default='require_review', help_text='Whether new document versions need reviewer approval before indexing.', max_length=20),
        ),
        migrations.RunPython(_backfill_direct_publish, migrations.RunPython.noop),
    ]
