# Generated by Django 5.0.14 on 2026-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0019_knowledgespace_review_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='taxonomy_mode',
            field=models.CharField(choices=[('inherit', 'Inherit Shared'), ('space', 'Space Private'), ('none', 'No Taxonomy')], default='inherit', help_text='How this space sources controlled taxonomy dimensions.', max_length=20),
        ),
        migrations.AddField(
            model_name='workspacecreaterequestdetail',
            name='taxonomy_init_mode',
            field=models.CharField(default='custom', max_length=20),
        ),
    ]
