# Generated by Django 5.0.14 on 2026-07-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0021_workspacecreate_reference_libraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Space Owner'), ('knowledge_admin', 'Knowledge Admin'), ('reviewer', 'Reviewer'), ('member', 'Member'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
