# Copyright (c) 2026 Haibo Fang.
# Licensed under the CC BY-NC-SA 4.0 License.
# See LICENSE file in the project root for full license details.

# Generated by Django 5.0.14 on 2026-06-17 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('document_upload', 'Document Upload'), ('document_delete', 'Document Delete'), ('document_reindex', 'Document Reindex'), ('document_status_change', 'Document Status Change'), ('template_create', 'Template Create'), ('template_update', 'Template Update'), ('template_delete', 'Template Delete'), ('user_login', 'User Login'), ('export_data', 'Export Data'), ('category_create', 'Category Create'), ('category_update', 'Category Update')], max_length=30)),
                ('target_type', models.CharField(help_text='Model name', max_length=100)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_auditlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
