# Copyright (c) 2026 Haibo Fang.
# Licensed under the CC BY-NC-SA 4.0 License.
# See LICENSE file in the project root for full license details.

# Generated by Django 5.0.14 on 2026-06-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_role_used_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('document_upload', 'Document Upload'), ('document_delete', 'Document Delete'), ('document_reindex', 'Document Reindex'), ('document_status_change', 'Document Status Change'), ('template_create', 'Template Create'), ('template_update', 'Template Update'), ('template_delete', 'Template Delete'), ('user_login', 'User Login'), ('export_data', 'Export Data'), ('category_create', 'Category Create'), ('category_update', 'Category Update'), ('role_assign', 'Role Assign'), ('role_revoke', 'Role Revoke'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_deactivate', 'User Deactivate'), ('config_change', 'Config Change'), ('system_health_view', 'System Health View'), ('audit_export', 'Audit Export'), ('role_change_log', 'Role Change Log'), ('document_crawl', 'Document Crawl'), ('document_crawl_withdraw', 'Document Crawl Withdraw')], max_length=30),
        ),
    ]
