# Generated by Django 5.0.14 on 2026-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('document_upload', 'Document Upload'), ('document_download', 'Document Download'), ('document_delete', 'Document Delete'), ('document_reindex', 'Document Reindex'), ('document_status_change', 'Document Status Change'), ('template_create', 'Template Create'), ('template_update', 'Template Update'), ('template_delete', 'Template Delete'), ('user_login', 'User Login'), ('export_data', 'Export Data'), ('category_create', 'Category Create'), ('category_update', 'Category Update'), ('role_assign', 'Role Assign'), ('role_revoke', 'Role Revoke'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_deactivate', 'User Deactivate'), ('config_change', 'Config Change'), ('system_health_view', 'System Health View'), ('ingestion_retry', 'Ingestion Retry'), ('audit_export', 'Audit Export'), ('role_change_log', 'Role Change Log'), ('document_crawl', 'Document Crawl'), ('document_crawl_withdraw', 'Document Crawl Withdraw'), ('document_batch_import', 'Document Batch Import'), ('document_batch_result_view', 'Document Batch Result View'), ('space_create', 'Space Create'), ('space_update', 'Space Update'), ('space_archive', 'Space Archive'), ('space_switch', 'Space Switch'), ('space_join', 'Space Join (Access Code)'), ('space_invite_create', 'Space Invite Code Create'), ('space_invite_revoke', 'Space Invite Code Revoke'), ('space_member_add', 'Space Member Add'), ('space_member_update', 'Space Member Update'), ('permission_denied', 'Permission Denied'), ('user_register', 'User Register'), ('admin_code_register', 'Admin Code Register'), ('admin_code_create', 'Admin Code Create'), ('admin_code_revoke', 'Admin Code Revoke'), ('space_member_remove', 'Space Member Remove'), ('space_email_invite', 'Space Email Invite'), ('notification_broadcast', 'Notification Broadcast'), ('signup_approved', 'Signup Approved'), ('signup_rejected', 'Signup Rejected'), ('user_promote_superadmin', 'User Promote Super Admin'), ('feedback_submit', 'Feedback Submit'), ('feedback_update', 'Feedback Update'), ('feedback_withdraw', 'Feedback Withdraw'), ('feedback_review_assign', 'Feedback Review Assign'), ('feedback_review_claim', 'Feedback Review Claim'), ('feedback_review_resolve', 'Feedback Review Resolve'), ('feedback_review_dismiss', 'Feedback Review Dismiss'), ('feedback_review_reopen', 'Feedback Review Reopen'), ('knowledge_gap_create', 'Knowledge Gap Create'), ('knowledge_gap_assign', 'Knowledge Gap Assign'), ('knowledge_gap_resolve', 'Knowledge Gap Resolve'), ('knowledge_gap_reopen', 'Knowledge Gap Reopen')], max_length=30),
        ),
    ]
