# Generated by Django 5.0.14 on 2026-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
