# Copyright (c) 2026 Haibo Fang.
# Licensed under the CC BY-NC-SA 4.0 License.
# See LICENSE file in the project root for full license details.

# Generated by Django 5.0.14 on 2026-06-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_batch_expansion_v4_2'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='knowledge_d_content_979d1d_idx',
            old_name='knowledge_doc_content_hash_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='spaces.knowledgespace'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='spaces.knowledgespace'),
        ),
    ]
