# Generated by Django 5.0.14 on 2026-07-02 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_ingestionjob'),
        ('spaces', '0004_adminregistrationcode_spaceemailinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['status', 'space', 'created_at'], name='know_ing_st_sp_cr_idx'),
        ),
    ]
