# Generated by Django 5.0.14 on 2026-07-26 13:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_document_text_content_and_file_nullable'),
        ('spaces', '0019_knowledgespace_review_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('active', 'Active'), ('stale', 'Stale'), ('archived', 'Archived'), ('expired', 'Expired'), ('failed', 'Failed'), ('superseded', 'Superseded'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anchor_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='knowledge.document')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='spaces.knowledgespace')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_documentlink',
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diff_summary', models.JSONField(blank=True, default=dict)),
                ('conflict_hints', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='knowledge.document')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='spaces.knowledgespace')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_reviewrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('is_hierarchical', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False, help_text='If true, uploads must carry at least one term.')),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_dimensions', to='spaces.businessline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_dimensions', to='spaces.organization')),
            ],
            options={
                'db_table': 'knowledge_taxonomydimension',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='knowledge.taxonomydimension')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.taxonomyterm')),
            ],
            options={
                'db_table': 'knowledge_taxonomyterm',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_tags', to='knowledge.document')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_documents', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='knowledge.taxonomyterm')),
            ],
            options={
                'db_table': 'knowledge_documenttag',
            },
        ),
        migrations.CreateModel(
            name='TermOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_terms', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_ownerships', to='spaces.knowledgespace')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='knowledge.taxonomyterm')),
            ],
            options={
                'db_table': 'knowledge_termownership',
            },
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='knowledge_doclink_src_tgt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reviewrequest',
            constraint=models.CheckConstraint(check=models.Q(('reviewer', models.F('submitted_by')), _negated=True), name='knowledge_review_reviewer_ne_submitter'),
        ),
        migrations.AddConstraint(
            model_name='reviewrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('decision', 'pending')), fields=('document',), name='knowledge_review_one_pending_per_doc'),
        ),
        migrations.AddConstraint(
            model_name='taxonomydimension',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='knowledge_taxdim_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyterm',
            constraint=models.UniqueConstraint(fields=('dimension', 'code'), name='knowledge_taxterm_dim_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='documenttag',
            constraint=models.UniqueConstraint(fields=('document', 'term'), name='knowledge_doctag_doc_term_uniq'),
        ),
        migrations.AddConstraint(
            model_name='termownership',
            constraint=models.UniqueConstraint(fields=('space', 'term', 'owner'), name='knowledge_termown_space_term_owner_uniq'),
        ),
    ]
