# Generated by Django 5.0.14 on 2026-07-27 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_purge_registry_review_models'),
        ('spaces', '0020_knowledgespace_taxonomy_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('ifrs', 'IFRS'), ('cas', 'China Accounting Standards'), ('ipo_cases', 'IPO Cases'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='unpublished', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_referencelibrary',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceLibraryReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_spacelibraryreference',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='taxonomydimension',
            name='knowledge_taxdim_org_code_uniq',
        ),
        migrations.AddField(
            model_name='taxonomydimension',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_dimensions', to='spaces.knowledgespace'),
        ),
        migrations.AddConstraint(
            model_name='taxonomydimension',
            constraint=models.UniqueConstraint(condition=models.Q(('space__isnull', True)), fields=('organization', 'code'), name='knowledge_taxdim_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='taxonomydimension',
            constraint=models.UniqueConstraint(condition=models.Q(('space__isnull', False)), fields=('space', 'code'), name='knowledge_taxdim_space_code_uniq'),
        ),
        migrations.AddField(
            model_name='referencelibrary',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_reference_libraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencelibrary',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_library', to='spaces.knowledgespace'),
        ),
        migrations.AddField(
            model_name='spacelibraryreference',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_library_references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacelibraryreference',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_references', to='knowledge.referencelibrary'),
        ),
        migrations.AddField(
            model_name='spacelibraryreference',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_references', to='spaces.knowledgespace'),
        ),
        migrations.AddIndex(
            model_name='referencelibrary',
            index=models.Index(fields=['status', 'category'], name='knowledge_reflib_status_cat'),
        ),
        migrations.AddConstraint(
            model_name='spacelibraryreference',
            constraint=models.UniqueConstraint(fields=('space', 'library'), name='knowledge_spacelibref_space_lib_uniq'),
        ),
    ]
