# Generated by Django 5.0.14 on 2026-07-28 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_referencelibrary_spacelibraryreference_and_more'),
        ('spaces', '0020_knowledgespace_taxonomy_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pooled_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='content_tokens',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DocumentSimilarity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_edges_out', to='knowledge.document')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_similarities', to='spaces.knowledgespace')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_edges_in', to='knowledge.document')),
            ],
            options={
                'db_table': 'knowledge_documentsimilarity',
                'indexes': [models.Index(fields=['space', '-score'], name='knowledge_d_space_i_114721_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentsimilarity',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='knowledge_docsim_src_tgt_uniq'),
        ),
    ]
