# Generated by Django 5.0.14 on 2026-07-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0017_document_pooled_embedding_and_more'),
        ('spaces', '0020_knowledgespace_taxonomy_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='unresolved_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyterm',
            name='synonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='knowledge.document'),
        ),
        migrations.AddConstraint(
            model_name='documentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('target__isnull', True)), fields=('source', 'unresolved_title'), name='knowledge_doclink_src_unres_uniq'),
        ),
    ]
