# Generated by Django 5.0.14 on 2026-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_referencelibrary_policy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='feedback_score',
            field=models.FloatField(default=0.0),
        ),
    ]
