# Generated by Django 5.0.14 on 2026-06-30 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('scenario_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('audit', 'Audit'), ('tax', 'Tax'), ('consulting', 'Consulting'), ('core_services', 'Core Business Services'), ('standards_qa', 'Standards QA'), ('project_ai', 'Project AI')], default='onboarding', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('quick_questions', models.JSONField(blank=True, default=list)),
                ('prompt_policy', models.JSONField(blank=True, default=dict)),
                ('retrieval_policy', models.JSONField(blank=True, default=dict)),
                ('default_visibility', models.CharField(choices=[('private', 'Private'), ('business_line', 'Business Line Internal'), ('organization', 'Organization Shared'), ('public_demo', 'Public Demo')], default='private', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenario_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scenario_templates_scenariotemplate',
                'ordering': ['name'],
            },
        ),
    ]
