# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenario_templates", "0001_initial"),
        ("spaces", "0004_adminregistrationcode_spaceemailinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariotemplate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional organization scope. Empty means global template.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario_templates",
                to="spaces.organization",
            ),
        ),
        migrations.AddField(
            model_name="scenariotemplate",
            name="business_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional business-line scope. Empty means global or organization-wide template.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario_templates",
                to="spaces.businessline",
            ),
        ),
    ]
