# Copyright (c) 2026 Haibo Fang.
# Licensed under the CC BY-NC-SA 4.0 License.
# See LICENSE file in the project root for full license details.

# Generated by Django 5.0.14 on 2026-06-17 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citation',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.documentchunk'),
        ),
        migrations.AddField(
            model_name='citation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.document'),
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.message'),
        ),
        migrations.AddField(
            model_name='citation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='chat.message'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('message',)},
        ),
    ]
