# Generated by Django 5.0.14 on 2026-06-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='spaces.knowledgespace'),
        ),
        migrations.AddField(
            model_name='citation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='spaces.knowledgespace'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='spaces.knowledgespace'),
        ),
        migrations.AddField(
            model_name='message',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='spaces.knowledgespace'),
        ),
    ]
