# Generated by Django 5.0.14 on 2026-07-02 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_feedback_v8(apps, schema_editor):
    Feedback = apps.get_model("chat", "Feedback")
    for feedback in Feedback.objects.select_related("message__session").all():
        message = feedback.message
        feedback.user_id = message.session.user_id
        if feedback.rating == 2:
            feedback.feedback_type = "helpful"
        elif feedback.reason == "outdated":
            feedback.feedback_type = "outdated"
        elif feedback.reason == "inaccurate":
            feedback.feedback_type = "incorrect"
        else:
            feedback.feedback_type = "unhelpful"
        feedback.status = "submitted"
        feedback.save(
            update_fields=[
                "user",
                "feedback_type",
                "status",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_modelinvocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('helpful', 'Helpful'), ('unhelpful', 'Unhelpful'), ('incorrect', 'Incorrect'), ('outdated', 'Outdated'), ('missing_source', 'Missing Source')], default='helpful', max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='flag_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolution_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='review_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggested_source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelinvocation',
            name='question_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_invocations_as_question', to='chat.message'),
        ),
        migrations.RunPython(backfill_feedback_v8, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Thumbs Down'), (2, 'Thumbs Up')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'message')},
        ),
    ]
