# Generated by Django 5.0.14 on 2026-07-02 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_feedback_unique_together_and_more'),
        ('spaces', '0004_adminregistrationcode_spaceemailinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('assign', 'Assign'), ('claim', 'Claim'), ('resolve', 'Resolve'), ('dismiss', 'Dismiss'), ('reopen', 'Reopen')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_review_events', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='chat.feedback')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback_review_events', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_review_events', to='spaces.knowledgespace')),
            ],
            options={
                'db_table': 'chat_feedbackreviewevent',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGapTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_snapshot', models.TextField()),
                ('normalized_question_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't Fix")], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('suggested_source', models.TextField(blank=True, default='')),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gap_tickets', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gap_tickets', to='chat.feedback')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_gap_tickets', to='spaces.knowledgespace')),
            ],
            options={
                'db_table': 'chat_knowledgegapticket',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['space', 'status', 'priority'], name='chat_gap_space_status_idx')],
            },
        ),
    ]
