# Generated by Django 5.0.14 on 2026-07-02 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_feedbackreviewevent_knowledgegapticket'),
        ('spaces', '0004_adminregistrationcode_spaceemailinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.CharField(choices=[('feedback', 'Feedback'), ('reviews', 'Reviews'), ('gaps', 'Knowledge Gaps'), ('unanswered', 'Unanswered Questions'), ('documents', 'Documents')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='queued', max_length=20)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.CharField(blank=True, default='', max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('safe_error_summary', models.CharField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_export_jobs', to='spaces.knowledgespace')),
            ],
            options={
                'db_table': 'chat_complianceexportjob',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status', '-created_at'], name='chat_export_request_status_idx'), models.Index(fields=['space', 'dataset', '-created_at'], name='chat_export_space_dataset_idx')],
            },
        ),
    ]
