# Generated by Django 5.0.14 on 2026-07-02 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_complianceexportjob'),
        ('spaces', '0004_adminregistrationcode_spaceemailinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complianceexportjob',
            index=models.Index(fields=['status', 'requested_by', 'created_at'], name='chat_exp_st_user_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['space', 'status', 'created_at'], name='chat_fb_sp_st_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgegapticket',
            index=models.Index(fields=['space', 'status', 'created_at'], name='chat_gap_sp_st_cr_idx'),
        ),
    ]
