# Generated by Django 5.0.14 on 2026-07-02 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_complianceexportjob_chat_exp_st_user_cr_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceexportjob',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='chat.complianceexportjob'),
        ),
    ]
