# Generated by Django 5.0.14 on 2026-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_session_reference_library_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='citation',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
